---
# tasks file for ansible_role_build_images

  - name: container_name
    ansible.builtin.debug:
      msg: "{{container_name}} {{container_image}}:{{container_image_tag}} ww4_import={{ww4_import|bool}} ww4_container={{ww4_container}} reg_export={{reg_export|bool}} reg_image={{reg_image}}:{{reg_image_tag}}"



  - name: Import the container to warewulf
    #ansible.builtin.shell: "wwctl container --update -v import file://{{tmp_folder_for_container.path}}/{{container_image}}_{{container_image_tag}}.tar {{ww4_container}}"
    ansible.builtin.shell: "wwctl container --update -v import docker://{{reg_image}}:{{reg_image_tag}} {{ww4_container}}"
    when: "ww4_import|bool"
    
