---
# tasks file for ansible_role_build_images

 - name: container_name
   ansible.builtin.debug:
      msg: "{{container_name}} {{base_container_image}}"

 - name: Check if the base container already exists
   ansible.builtin.command: "podman container exists {{ container_name }}"
   register: base_container_exists
   changed_when: False
   failed_when: base_container_exists.rc not in [0,1]


 - name: Log in to a container registry using Podman
   command: "podman login -u {{ registry_username }} -p {{ registry_password }} {{ registry_url }}"
   when: registry_url is defined and registry_username is defined and registry_password is defined and registry_url | length > 0 and registry_username | length > 0 and registry_password | length > 0


# This is done in a separate step to allow for auth_file
# - name: Pull the base container image
#   containers.podman.podman_image:
#      name: "{{base_container_image}}"
#      auth_file: "{{ registry_auth_file }}"
#   register: base_container_image_information

# - name: Print base_container_image_information
#   ansible.builtin.debug:
#      msg: "{{base_container_image_information}}"
#
# - name: Print base_container_image_information of image 0 id
#   ansible.builtin.debug:
#      msg: "{{base_container_image_information['image'][0]['Id']}}"

 - name: Make sure there is no base container yet
   containers.podman.podman_container:
      name: "{{container_name}}"
      state: absent
   when: '"remove_base_container" and base_container_exists.rc == 0'


 - name: Create and start the base container (recreate=yes)
   containers.podman.podman_container:
      name:  "{{container_name}}"
      image: "{{base_container_image}}"
#      image: "{{base_container_image_information['image'][0]['Id']}}" # use this to force using the local image and not pulling without auth_file
      state: "started"
      remove: yes
      entrypoint: "/usr/sbin/init"
      #init: yes
      recreate: yes
   when: base_container_exists.rc != 0

 - name: Start the base container
   containers.podman.podman_container:
      name:  "{{container_name}}"
      image: "{{base_container_image}}"
#      image: "{{base_container_image_information['image'][0]['Id']}}" # use this to force using the local image and not pulling without auth_file
      state: "started"
      remove: yes
      entrypoint: "/usr/sbin/init"
   when: base_container_exists.rc == 0
