---
# tasks file for ansible_role_build_images

  - name: container_name
    ansible.builtin.debug:
      msg: "{{container_name}} {{container_image}}:{{container_image_tag}} ww4_import={{ww4_import|bool}} ww4_container={{ww4_container}} reg_export={{reg_export|bool}} reg_image={{reg_image}}:{{reg_image_tag}}"


  # Is there really no role for this task?
  - name: Podman-commit the image
    ansible.builtin.shell: "podman commit --pause {{container_name}} {{reg_image}}:{{container_image_tag}}"

  - name: Stop the container
    containers.podman.podman_container:
      name: "{{container_name}}"
      state: stopped

  # allow multiple tags via reg_image_tag array
  - name: Podman-tag the image for export 
    containers.podman.podman_tag:
      image: "{{reg_image}}:{{container_image_tag}}"
      target_names:
      - "{{ reg_image }}:{{ tagitem }}"
    when: reg_export and tagitem != container_image_tag
    loop: "{{ reg_image_tag }}"
    loop_control:
      loop_var: tagitem

  # Make sure to
  # - "podman login {{registry_url}}" first manually!
  # - "cp ${XDG_RUNTIME_DIR}/containers/auth.json {{ registry_auth_file }}"
  - name: Push the image to the registry
    containers.podman.podman_image:
      name: "{{ reg_image }}:{{ tagitem }}"
      push: yes
#      validate_certs: false
      auth_file: "{{ registry_auth_file }}"
    when: "reg_export|bool"
    loop: "{{ reg_image_tag }}"
    loop_control:
      loop_var: tagitem
